# General
base_url = "https://leokang28.github.io"
theme = "anemone"
compile_sass = false
minify_html = true
generate_feeds = true
generate_sitemap = true
title = "KSLEO"
description = ""

# Taxonomies
taxonomies = [
    {name = "tags", feed = true, paginate_by = 5},
]

# Language
default_language = "en"
build_search_index = true

# [languages.zh]
# build_search_index = true
# title = "KSLEO"
# description = ""

[markdown]
render_emoji = true
external_links_target_blank = true
smart_punctuation = true
highlight_code = false
highlight_theme = "gruvbox-dark"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[link_checker]
internal_level = "warn"

# Extra
[extra]
author = "ksleo"
favicon = "favicon.ico"
list_pages = true
display_published = true

display_author = true
twitter_card = true
enable_search = true

## Navigation
header_nav = [
  { url = "/archive", name_en = "/archive", name_zh = "/archive" },
  { url = "/tags", name_en = "/tags", name_zh = "/tags" },
  { url = "/about", name_en = "/about", name_zh = "/about" }
]
